export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_REQUEST_SUCCESS = 'RESET_PASSWORD_REQUEST_SUCCESS'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'

export const ME_REQUEST = 'ME_REQUEST'
export const ME_REQUEST_SUCCESS = 'ME_REQUEST_SUCCESS'
export const ME_UPDATE_REQUEST = 'ME_UPDATE_REQUEST'
export const ME_UPDATE_REQUEST_SUCCESS = 'ME_UPDATE_REQUEST_SUCCESS'

export const DASHBOARD_REQUEST = 'DASHBOARD_REQUEST'
export const DASHBOARD_REQUEST_SUCCESS = 'DASHBOARD_REQUEST_SUCCESS'

export const USERS_REQUEST = 'USERS_REQUEST'
export const USERS_REQUEST_SUCCESS = 'USERS_REQUEST_SUCCESS'
export const USERS_RESET_REQUEST = 'USERS_RESET_REQUEST'
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_REQUEST_SUCCESS = 'USER_DETAILS_REQUEST_SUCCESS'
export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_REQUEST_SUCCESS = 'USER_DELETE_REQUEST_SUCCESS'
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_REQUEST_SUCCESS = 'USER_UPDATE_REQUEST_SUCCESS'
export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST'
export const USER_CREATE_REQUEST_SUCCESS = 'USER_CREATE_REQUEST_SUCCESS'
export const USER_RESET_REQUEST = 'USER_RESET_REQUEST'

export const REQUEST_START = 'REQUEST_START'
export const REQUEST_END = 'REQUEST_END'

export const ALERT_ERROR = 'ALERT_ERROR'
export const ALERT_SUCCESS = 'ALERT_SUCCESS'

export const NAVIGATE = 'NAVIGATE'
export const BACK = 'BACK'

export const REHYDRATE = 'persist/REHYDRATE'
